# Generated by Django 4.0.6 on 2022-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='timeframe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
