# Generated by Django 4.0.6 on 2022-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_data_convertedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='convertedfile',
        ),
        migrations.AddField(
            model_name='data',
            name='convertedfile_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
